apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flask-sample 
spec: 
  selector: 
    matchLabels: 
      app: flask-sample 
  replicas: 3
  template:
    metadata: 
      labels: 
        app: flask-sample 
    spec: 
      containers: 
      - name: angular 
        image: raghuramlavan/flask-sample:latest
        ports: 
        - containerPort: 80 

# service
kind: Service 
apiVersion: v1 
metadata: 
  name: flask-sample 
spec: 
  selector: 
    app: flask-sample 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
